### ISSUE TITLE
Documentation Support Crossover

### ISSUE THREAD

**Issue by jwafu** [pieces-app/documentation#268]
## Overview 
Our goal is to get the documentation on a release cycle with a detailed process that allows us to fold in updates from support, product and also upgrades to pages that currently exist and need updates. 

### Details 
**Cycle Process Time** - 2 week cycles  

### Topics/Resources to Include 
- [ ] new issues based on top support tickets | @rosie-at-pieces is handling this 
- [ ] product updates throughout the ecosystem (reviewing together on wednesday)
- [ ] backlog/outstanding issues | @jordan-pieces is handling this
- [ ] new components + components that we want upgraded | @jordan-pieces is handling this 

--- 

#### New Issues from Support 
- [ ] 

#### Product Updates 
- [ ] 

#### Backlog on Docs 
- [ ] Migrate Gifs to new Rounded Gifs on Copilot Page: https://github.com/pieces-app/documentation/issues/250
- [ ] Connecting to a Remote Pieces Instance Update: https://github.com/pieces-app/documentation/issues/266

#### Component Updates & New Components
- [x] Button Updates to Match rest of site: https://github.com/pieces-app/documentation/issues/263

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces this will be updated prob next week or the week after once we get the migration merged in.

I think the general basis is to have an issue for any changes that are needed, then add those issues to the current milestone. Then we can do a release once they are completed.

Then obviously we have a set amount of issues per milestone.

I think the 2 week cadence is fine to keep though.

**Comment by rosie-at-pieces** [comment]
that sounds like a great plan to me!

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces Gonna close this since I've made all the current changes and then you can simply just create issues and assign them to me as they come in 👍
