### ISSUE TITLE
Remove Unneeded Redirects + Relocate extensions, plugins support -> plugins/extensions

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#38]
- [x] Move pages to extensions-plugins 
- [x] Add redirects to extensions-plugins-support/*
- [x] Remove old redirect pages 
- [x] add install page illustrations 
- [x] move gif down low, rework sections order + remove youtube banner 
- [x] Set task for SEO Audit at EOM (31st May)
- [x] add teams to the products section
- [x] update logo in the footer of index
- [x] move installation section up to the top
